=== caojincool/dubbo-basic-platform/x5-tools/modules/sqlgen/sqlgen/sqlgen.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.jee-soft.cn/sqlgen"
    targetNamespace="http://www.jee-soft.cn/sqlgen" elementFormDefault="qualified">
    <xs:element name="resources">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="resource" type="resource" minOccurs="1" maxOccurs="unbounded"></xs:element>
            </xs:sequence>
            <xs:attribute name="filePath" type="xs:string" use="required"> 
	            <xs:annotation>
	                <xs:documentation>生成文件路径.</xs:documentation>
	            </xs:annotation>
            </xs:attribute>
                <xs:attribute name="isEndSql" type="xs:boolean" default="true"> 
	            <xs:annotation>
	                <xs:documentation>是否生成结束SQL【commit】.</xs:documentation>
	            </xs:annotation>
            </xs:attribute>
            
        </xs:complexType>
        
    </xs:element>

    <xs:complexType name="resource">
        <xs:all>
            <xs:element name="sql" type="xs:string" >
                <xs:annotation>
                    <xs:documentation>SQL语句.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="template" type="xs:string">
                <xs:annotation>
                    <xs:documentation>生成SQL模版.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:all>
        <xs:attribute name="table" type="xs:string" use="required">
            <xs:annotation>
                <xs:documentation>表名.</xs:documentation>
            </xs:annotation>
        </xs:attribute>
        <xs:attribute name="pk" type="xs:string" use="required">
            <xs:annotation>
                <xs:documentation>主键.</xs:documentation>
            </xs:annotation>
        </xs:attribute>
        <xs:attribute name="parentId" type="xs:string">
            <xs:annotation>
                <xs:documentation>父类ID.</xs:documentation>
            </xs:annotation>
        </xs:attribute>
        <xs:attribute name="parentIdVal" type="xs:string">
            <xs:annotation>
                <xs:documentation>父类ID值.</xs:documentation>
            </xs:annotation>
        </xs:attribute>
        <xs:attribute name="variables" type="xs:string">
            <xs:annotation>
                <xs:documentation>变量JSON【格式：{'key':'value'}】.</xs:documentation>
            </xs:annotation>
        </xs:attribute>
        <xs:attribute name="mainTable" type="xs:string">
            <xs:annotation>
                <xs:documentation>主表表名.</xs:documentation>
            </xs:annotation>
        </xs:attribute>
        <xs:attribute name="fk" type="xs:string" >
            <xs:annotation>
                <xs:documentation>外键.</xs:documentation>
            </xs:annotation>
        </xs:attribute>
    </xs:complexType>
</xs:schema>

=== caojincool/dubbo-basic-platform/x5-tools/modules/sqlgen/sqlgen/sqlgen.xml
<?xml version="1.0" encoding="UTF-8"?>
<resources xmlns="http://www.jee-soft.cn/sqlgen"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.jee-soft.cn/sqlgen sqlgen.xsd"
    filePath="D:\init.sql" >
	
	 <resource table="sys_type_group" pk="id_">
	 	<sql>
	 		SELECT * from sys_type_group
	 	</sql>
	 	<template>
	 		insert into sys_type_group (id_,group_key_,name_,flag_,sn_,type_) 
	 		values ('${ID_}','${GROUP_KEY_}','${NAME_}','${FLAG_}','${SN_}','${TYPE_}');
	 	</template>
	 </resource>
	 
	 <resource table="bpm_selector_def" pk="id_">
	 	<sql>
	 		select * from bpm_selector_def
	 	</sql>
	 	<template>
	 		insert into bpm_selector_def (id_, name_, alias_, group_field_, buttons_, is_custom_, flag_, method_, conf_key_)
	 		values ('${ID_}', '${NAME_}', '${ALIAS_}', '${GROUP_FIELD_}', '${BUTTONS_}', '${IS_CUSTOM_}', '${FLAG_}', '${METHOD_}', '${CONF_KEY_}');
	 	</template>
	 </resource>
	 
	 <resource table="sys_msg_tpl" pk="id_">
	 	<sql>
	 		select * from sys_msg_tpl
	 	</sql>
	 	<template>
	 		INSERT INTO sys_msg_tpl (id_, name_, key_, type_key_, is_default_, subject_, plain_, html_)
	 		values ('${ID_}', '${NAME_}', '${KEY_}', '${TYPE_KEY_}', ${IS_DEFAULT_}, '${SUBJECT_}', '${PLAIN_}', '${HTML_}');
	 	</template>
	 </resource>
	 
	 <resource table="sys_properties" pk="id">
	 	<sql>
	 		select * from sys_properties
	 	</sql>
	 	<template>
			INSERT INTO SYS_PROPERTIES (id,name,alias,group_,value,encrypt,description)
			VALUES ('${ID}', '${NAME}', '${ALIAS}', '${GROUP_}', '${VALUE}', ${ENCRYPT}, '${DESCRIPTION}');
		</template>
	 </resource>
	 
	<resource table="custom_dialog" pk="id_">
		<sql>
			select * from custom_dialog
		</sql>
		<template>
			insert into custom_dialog (id_,name_,alias_,style_,obj_name_,need_page_,page_size_,displayfield_,conditionfield_,resultfield_,sortfield_,dsalias_,is_table_,diy_sql_,sql_build_type_,width_,height_,select_num_,system_)
			values ('${ID_}','${NAME_}','${ALIAS_}','${STYLE_}','${OBJ_NAME_}',${NEED_PAGE_},${PAGE_SIZE_},'${DISPLAYFIELD_}','${CONDITIONFIELD_}','${RESULTFIELD_}','${SORTFIELD_}','${DSALIAS_}',${IS_TABLE_},'${DIY_SQL_}','${SQL_BUILD_TYPE_}',${WIDTH_?c},${HEIGHT_?c},${SELECT_NUM_},${SYSTEM_});
		</template>
	</resource>
	
	<resource table="sys_script" pk="ID_">
		<sql>select * from  SYS_SCRIPT</sql>
		<template>
			INSERT INTO SYS_SCRIPT(ID_,NAME_,SCRIPT_,CATEGORY_,MEMO_)
			values ('${ID_}','${NAME_}','${SCRIPT_}','${CATEGORY_}','${MEMO_}');
		</template>
	</resource>
	
	

	<resource table="base_sys_resource" pk="ID_"  parentId="PARENT_ID_" parentIdVal="0" 
	variables="{'SYSTEMID':'1'}">
		<sql>SELECT * FROM  base_sys_resource where SYSTEM_ID_ ='${SYSTEMID}' AND PARENT_ID_='${PARENT_ID_}' ORDER BY SN_</sql>
		<template>
		<![CDATA[INSERT INTO base_sys_resource (ID_,SYSTEM_ID_,ALIAS_,NAME_,default_url_,ENABLE_MENU_,HAS_CHILDREN_,OPENED_,ICON_,NEW_WINDOW_,SN_,PARENT_ID_)
		VALUES  ('${ID_}', '${SYSTEM_ID_}', '${ALIAS_}', '${NAME_}', '${DEFAULT_URL_}', ${ENABLE_MENU_}, ${HAS_CHILDREN_}, ${OPENED_}, '${ICON_}', ${NEW_WINDOW_}, '<#if (SN_)??>${SN_?c}<#else>0</#if>','${PARENT_ID_}');]]>
		</template>
	</resource>


</resources>
